import type { App } from '../types'

export const apps: App[] = [
  {
    id: 'resume-ai',
    title: 'ResumeAI',
    tagline: 'Tailor your CV to any job in 60 seconds',
    link: 'https://resumeai.example.com',
    creatorId: 'kimdev',
    description: 'Paste a job description, upload your resume, get a tailored version instantly. No prompt engineering needed.',
    useCases: [
      'Tailor your CV to a specific job posting',
      'Match keywords from the job description automatically',
      'Keep your original voice and formatting',
    ],
    tags: ['resume', 'job search', 'writing', 'AI'],
    category: 'writing',
    accessType: ['web'],
    pricing: 'free',
    storyCard: {
      problemStatement: 'Tailoring your CV to every job description takes way too long',
      solutionStatement: 'Paste a job description. Upload your resume. Get a tailored version in 60 seconds.',
      features: ['Matches keywords automatically', 'Keeps your original voice', 'Works with any file format'],
      gradientTheme: 'indigo-purple',
      shareableUrl: '/story/resume-ai',
    },
    socialCopy: {
      twitter: "Spent 2 hours tailoring my resume last week 😤\n\nResumeAI does it in 60 seconds. Paste the job description, upload your CV, done.\n\nFree → [link]",
      linkedin: "I built a free tool that makes resume tailoring instant.\n\nResumeAI reads any job description and rewrites your CV to match — automatically, in your voice.",
    },
    boostCount: 243,
    isNew: true,
  },
  {
    id: 'pixeldrop',
    title: 'PixelDrop',
    tagline: 'Upload once, get every image size instantly',
    link: 'https://pixeldrop.example.com',
    creatorId: 'kimdev',
    description: 'Resize any image for every platform in seconds. No Photoshop, no Canva — just upload and download.',
    useCases: [
      'Resize product photos for Shopify',
      'Prep images for Instagram, Twitter, and LinkedIn at once',
      'Remove backgrounds without design software',
    ],
    tags: ['images', 'resize', 'design', 'social media'],
    category: 'images',
    accessType: ['web'],
    pricing: 'free',
    storyCard: {
      problemStatement: 'Resizing images for every platform wastes hours every week',
      solutionStatement: 'Upload once, get every size instantly — no design skills needed.',
      features: ['Batch resize any image', 'Exports for all major platforms', 'Background removal included'],
      gradientTheme: 'sky-indigo',
      shareableUrl: '/story/pixeldrop',
    },
    socialCopy: {
      twitter: "Stop wasting 20 mins resizing images before every post 😤\n\nPixelDrop does it in 3 seconds. Upload once → get every size.\n\nFree → [link]",
      linkedin: "I built a free tool that saves social media managers ~2 hours per week.\n\nPixelDrop automatically resizes any image for Instagram, Twitter, LinkedIn, and more — in one click.",
    },
    boostCount: 512,
    isNew: false,
  },
  {
    id: 'voicenote-pro',
    title: 'VoiceNote Pro',
    tagline: 'Transcribe and summarize your voice memos automatically',
    link: 'https://voicenotepro.example.com',
    creatorId: 'novatech',
    description: 'Record a voice note, get a clean transcription, summary, and action items — automatically.',
    useCases: [
      'Turn meeting voice notes into structured summaries',
      'Extract action items from recorded ideas',
      'Search across all your voice memos',
    ],
    tags: ['audio', 'transcription', 'productivity', 'notes'],
    category: 'audio',
    accessType: ['web'],
    pricing: 'freemium',
    storyCard: {
      problemStatement: 'Voice recordings are messy and impossible to search or act on',
      solutionStatement: 'Record, transcribe, summarize, and extract action items — automatically.',
      features: ['Accurate transcription in 30+ languages', 'AI summary + action items', 'Full-text search across all memos'],
      gradientTheme: 'emerald-sky',
      shareableUrl: '/story/voicenote-pro',
    },
    socialCopy: {
      twitter: "I used to lose half my best ideas because voice notes are chaos.\n\nVoiceNote Pro transcribes, summarizes, and extracts action items automatically.\n\nFree to try → [link]",
      linkedin: "Every voice memo I record becomes a searchable, structured note automatically.",
    },
    boostCount: 187,
    isNew: true,
  },
  {
    id: 'blogai',
    title: 'BlogAI',
    tagline: 'Turn rough notes into polished blog posts',
    link: 'https://blogai.example.com',
    creatorId: 'writesmart',
    description: 'Paste your bullet points or rough notes and get a full, well-structured blog post written in your style.',
    useCases: [
      'Turn LinkedIn drafts into full articles',
      'Expand bullet notes into structured posts',
      'Generate multiple variations to choose from',
    ],
    tags: ['writing', 'blogging', 'content', 'AI'],
    category: 'writing',
    accessType: ['web'],
    pricing: 'freemium',
    storyCard: {
      problemStatement: 'Turning rough notes into polished blog posts takes hours of painful rewriting',
      solutionStatement: 'Paste your notes, get a full blog post in your voice — in under a minute.',
      features: ['Works from bullet points or rough drafts', 'Matches your writing style', 'Multiple variations generated'],
      gradientTheme: 'indigo-purple',
      shareableUrl: '/story/blogai',
    },
    socialCopy: {
      twitter: "My notes were great. My blog posts were not.\n\nBlogAI fixes that. Paste your rough notes → get a polished post.\n\nFree → [link]",
      linkedin: "The gap between a great idea and a great blog post used to be 3 hours of rewriting.",
    },
    boostCount: 318,
    isNew: false,
  },
  {
    id: 'launchkit',
    title: 'LaunchKit',
    tagline: 'Go from idea to launched product page in minutes',
    link: 'https://launchkit.example.com',
    creatorId: 'shipfast',
    description: 'Generate a complete product page — copy, design, waitlist form — from a one-paragraph description.',
    useCases: [
      'Launch a waitlist page before you build',
      'Test product ideas with a real landing page',
      'Ship your first version without a designer',
    ],
    tags: ['launch', 'landing page', 'startup', 'no-code'],
    category: 'business',
    accessType: ['web'],
    pricing: 'freemium',
    storyCard: {
      problemStatement: 'Setting up a product page before launch takes days of design and copywriting work',
      solutionStatement: 'Describe your product in one paragraph. Get a complete launch page in minutes.',
      features: ['Full page copy generated', 'Built-in waitlist form', 'One-click publish'],
      gradientTheme: 'orange-amber',
      shareableUrl: '/story/launchkit',
    },
    socialCopy: {
      twitter: "Built a product page in 8 minutes yesterday.\n\nLaunchKit generates everything — copy, layout, waitlist form — from a description.\n\nFree to try → [link]",
      linkedin: "You should be testing product ideas with real landing pages, not just talking about them.",
    },
    boostCount: 401,
    isNew: false,
  },
]
